Author: ****

# 3. Reading and writing files

### Goals

- reading the atom coordinates from a PDB file
- output value tables to a text file
- learning to do calculations with *numpy arrays*
- first plotting with *matplitlib*

### Introduction

#### ATOM data in PDB files

The PDB file format contains information about atom species and positions. This information is found in lines starting with ``ATOM``. Each of these lines has the same amount of characters and has the following format:

| Characters | Type                                  | Data type        |       
|------------|---------------------------------------|------------------|
| 1 - 6      | Record name «ATOM»                    | String           |
| 7-11       | Serial atom number                    | Integer          |
| 13-16      | Atom name                             | String           |
| 17         | Alternate location                    | String           |
| 18-20      | Residue name                          | String           |
| 22         | Chain identifier                      | String           |
| 23-26      | Residue sequence nb.                  | Integer          |
| 27         | Code for residues insertion           | String           |
| 31-38      | X coordinate in Å                     | Float            |
| 39-46      | Y coordinate in Å                     | Float            |
| 47-54      | Z coordinate in Å                     | Float            |
| 55-60      | Occupancy                             | Float            |
| 61-66      | Temperature factor                    | Float            |
| 77-78      | Element symbol (right justified!)     | String           |
| 79-80      | Charge                                | String           |

Further reading: http://www.wwpdb.org/documentation/file-format-content/format33/v3.3.html

**Note:** With PDB files, splitting the lines in their individual columns using the function ``line.split()`` is dangerous: use character positions instead!

### *TASK 1*

In this folder you will find the PDB file for Proaerolysin (``1PRE.pdb``). Open the file, and print all the lines containing a cysteine (residue name "CYS"). 

**Note:** Remember that in *Python* one starts counting from 0, not 1!

In [6]:
# TYPE YOUR SOLUTION HERE

with open('1PRE.pdb', 'r') as file_handle:
    lines = file_handle.readlines()
    for line in lines:
        if line.startswith('ATOM') and line[18-1:20+1-1] == 'CYS':
            print(line)
            

ATOM    136  N   CYS A  19      13.459  82.830  23.230  1.00 33.86           N  

ATOM    137  CA  CYS A  19      12.542  81.712  23.122  1.00 33.54           C  

ATOM    138  C   CYS A  19      11.546  81.890  21.995  1.00 34.09           C  

ATOM    139  O   CYS A  19      11.397  82.988  21.465  1.00 34.19           O  

ATOM    140  CB  CYS A  19      11.740  81.685  24.443  1.00 32.44           C  

ATOM    141  SG  CYS A  19      12.815  81.107  25.800  1.00 31.70           S  

ATOM    561  N   CYS A  75      13.304  76.650  26.884  1.00 28.69           N  

ATOM    562  CA  CYS A  75      12.218  77.532  27.304  1.00 30.01           C  

ATOM    563  C   CYS A  75      11.060  76.742  27.879  1.00 30.85           C  

ATOM    564  O   CYS A  75      11.022  75.512  27.695  1.00 31.27           O  

ATOM    565  CB  CYS A  75      11.760  78.281  26.056  1.00 30.28           C  

ATOM    566  SG  CYS A  75      13.153  79.155  25.299  1.00 30.92           S  

ATOM   1211  N  

### *TASK 2*

Parse ``1PRE.pdb`` and write the $x$, $y$ and $z$ coordinates of all the cysteines to the output file ``atoms_cys.txt``. Use [*f-strings*](https://www.blog.pythonlibrary.org/2018/03/13/python-3-an-intro-to-f-strings/) to generate one string for each line ending with a newline character ``\n``.

**Advanced:** Make sure that columns are aligned.

In [11]:
# TYPE YOUR SOLUTION HERE

with open('1PRE.pdb', 'r') as file_handle:
    lines = file_handle.readlines()
    lines_output = []
    for line in lines:
        if line.startswith('ATOM') and line[18-1:20+1-1] == 'CYS':
            x = float(line[31-1:38+1-1])
            y = float(line[39-1:46+1-1])
            z = float(line[47-1:54+1-1])
            line_output = f"{x}\t{y}\t{z}\n"
            lines_output.append(line_output)

with open('atoms_cys.txt', 'w') as file_handle:
    file_handle.writelines(lines_output)

### *TASK 3*

Define a function ``read_pdb(filename)`` that expects as input parameter a PDB filename and that returns four *numpy arrays* containing
- the $x$ coordinates
- the $y$ coordinates
- the $z$ coordinates
- the atom numbers (proton numbers)

**Advanced:** Save the function in another file called ``pdb_``*yourname*``.py``, import and call it.

In [2]:
# Import of numpy
import numpy

In [3]:
# TYPE YOUR SOLUTION HERE

proton_number = {'C' : 6, 'N' : 7, 'O' : 8, 'S' : 16}

def read_pdb(filename='1PRE.pdb'):
    X = []
    Y = []
    Z = []
    A = []
    with open(filename, 'r') as file_handle:
        lines = file_handle.readlines()
        lines_output = []
        for line in lines:
            if line.startswith('ATOM') and line[18-1:20+1-1] == 'CYS':
                x = float(line[31-1:38+1-1])
                y = float(line[39-1:46+1-1])
                z = float(line[47-1:54+1-1])
                element = line[77-1:78+1-1].lstrip()
                a = proton_number[element]
                X.append(x)
                Y.append(y)
                Z.append(z)
                A.append(a)
    X = numpy.array(X)
    Y = numpy.array(Y)
    Z = numpy.array(Z)
    A = numpy.array(A)
    return (X, Y, Z, A)

read_pdb()  

(array([ 13.459,  12.542,  11.546,  11.397,  11.74 ,  12.815,  13.304,
         12.218,  11.06 ,  11.022,  11.76 ,  13.153, -34.683, -33.997,
        -34.829, -36.037, -32.829, -33.275, -33.025, -31.971, -31.642,
        -30.709, -32.142, -33.612,  17.737,  18.669,  19.747,  19.92 ,
         19.421,  18.646,  18.284,  19.436,  20.647,  20.941,  19.759,
         18.303,  65.931,  65.302,  66.332,  67.553,  64.291,  65.036,
         64.657,  63.676,  63.314,  62.193,  64.068,  65.516]),
 array([82.83 , 81.712, 81.89 , 82.988, 81.685, 81.107, 76.65 , 77.532,
        76.742, 75.512, 78.281, 79.155, 48.263, 49.53 , 50.797, 50.849,
        49.678, 49.564, 52.464, 52.007, 50.547, 50.075, 52.251, 51.54 ,
        73.52 , 73.085, 74.16 , 74.938, 71.86 , 70.235, 67.714, 67.773,
        66.978, 66.772, 69.237, 70.128, 40.911, 41.248, 41.648, 41.729,
        42.383, 43.979, 47.952, 46.891, 46.637, 46.172, 45.624, 44.746]),
 array([23.23 , 23.122, 21.995, 21.465, 24.443, 25.8  , 26.884, 27.304,
    

### *TASK 4*

Use the *matplotlib* function [*matplotlib.pyplot.scatter* ](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.scatter.html) to visualise the $x$ and $y$ coordinates of Proaerolysin.

**Advanced:** Plot each element in a different color.

In [22]:
# Magic import of the matplotlib package for activating plotting in the notebook
import matplotlib
%matplotlib inline

In [29]:
# TYPE YOUR SOLUTION HERE
X, Y, Z, A = read_pdb()

#matplotlib.pyplot.scatter

### *EXTRA TASK*

The radius of gyration of a molecule of $N$ atoms is defined as
    
$$R_g = \sqrt{\frac{\sum_i^N m_i r_i^2}{\sum_i^N m_i}}$$

where $m_i$ is mass of atom $i$ and $r_i$ is the distance of atom $i$ from the molecule's center of mass

$$\vec{r_0} = \frac{\sum_i^N m_i \vec{r_i}}{\sum_i^N m_i}$$

Estimate the size of Proaerolysin by calculating the radius of gyration on the basis of only its carbon atoms.

**Advanced:** Consider atoms of all elements for this calculation.

In [25]:
# TYPE YOUR SOLUTION HERE